### ISSUE TITLE
Add Travis/Appveyor/Codecov

### ISSUE THREAD

**Issue by dlfivefifty** [idlemat/PowerNumbers.jl#9]

**Comment by idlemat** [comment]
Is this to add only one or all of these?

**Comment by dlfivefifty** [comment]
I believe now that Travis supports Windows you no longer need Appveyor. (Windows is useful since its the only 32-bit OS left which catches bugs.) 

Codecov is different: it determines which lines of your code are tested in the unit tests, and will check PRs to make sure they cover new code added.
